// ─── Database Row Types ───────────────────────────────────────────────────────
// These mirror the Supabase (PostgreSQL) table schemas exactly.
// Each field name matches the database column name.

/** Allowed tokens in `profiles.position` (`text[]` in Postgres). */
export type VolleyballPosition =
  | 'setter'
  | 'libero'
  | 'outside_hitter'
  | 'defensive_specialist'
  | 'opposite_hitter'

/**
 * `profiles` table
 * Created automatically by a database trigger when a user signs up via Supabase Auth.
 * The `id` matches `auth.users.id` (UUID).
 */
export type Profile = {
  id: string            // Primary key — same UUID as the auth user
  username: string      // Unique, lowercase display name chosen at registration
  first_name: string | null
  last_name: string | null
  /** Storage object path in `avatars` bucket (private) or legacy `https://…` public URL. */
  avatar_url: string | null
  /** Preferred positions (`text[]`); empty array means none chosen. */
  position: VolleyballPosition[]
  created_at: string    // ISO 8601 — when the account was created
  is_admin?: boolean  // default false; only true for club/platform admins
  /** Per-channel toggles keyed by notification_type; omitted keys default to on server-side. */
  notification_prefs?: NotificationPrefs | null
  /** Currently equipped profile border; null means no border. */
  selected_border?: 'bronze' | 'gold' | 'gradient' | null
  /** Currently equipped profile card background; null means default. */
  selected_card_bg?: CardBgType | null
  /** Optional short bio, max 140 characters. */
  bio?: string | null
}

/** Values must stay in sync with `notifications.notification_type` check constraint in Supabase. */
export const NOTIFICATION_TYPES = [
  'event_announcement',
  'cheers_received',
  'event_material_change',
  'waitlist_promoted',
  'event_cancelled',
  'badge_earned',
  'cohost_added',
] as const

export type NotificationType = (typeof NOTIFICATION_TYPES)[number]

/** Stored in `profiles.notification_prefs` jsonb. */
export type NotificationPrefs = {
  in_app: Partial<Record<NotificationType, boolean>>
  push: Partial<Record<NotificationType, boolean>>
}

/** Payload for `notifications.data` (ids for deep links; keep additive). */
export type NotificationData = {
  event_id?: string
  comment_id?: string
  cheer_id?: string
  deep_link?: string
  badge_type?: string
}

/**
 * `notifications` table — per-user inbox (inserted by DB triggers only).
 */
export type Notification = {
  id: string
  user_id: string
  notification_type: NotificationType
  title: string
  body: string
  data: NotificationData
  read_at: string | null
  created_at: string
}

/**
 * `events` table
 * Stores all events created by users.
 */
export type Event = {
  id: string                   // Primary key — UUID auto-generated by the DB
  created_by: string           // FK → profiles.id — the user who created this event
  title: string                // Required — shown everywhere an event is listed
  description: string | null   // Optional — longer details about the event
  location: string | null      // Optional — venue name or address
  event_date: string           // ISO 8601 — when the event takes place
  duration_minutes: number     // How long the event runs; default 120 (2 hours)
  max_attendees: number | null // Optional capacity cap; null means unlimited
  created_at: string           // ISO 8601 — when this row was inserted
  club_id: string | null       // Optional FK → clubs.id
  /** Set when the host cancels the event (nullable until migration applied). */
  cancelled_at?: string | null
}

/** Cheer categories for post-event peer recognition */
export type CheerType =
  | 'spike'
  | 'block'
  | 'serve'
  | 'dig'
  | 'set'
  | 'pass'
  | 'communication'

/**
 * `cheers` table
 * One row per (event, giver, receiver, type). Given after an event ends.
 * Unique constraint: (event_id, giver_id, receiver_id, cheer_type).
 */
export type Cheer = {
  id: string
  event_id: string
  giver_id: string
  receiver_id: string
  cheer_type: CheerType
  created_at: string
}

/**
 * `event_attendees` join table
 * One row per (event, user) pair. Inserting a row = joining an event.
 * Deleting a row = leaving an event.
 * There is no separate "attendee ID" — the composite (event_id, user_id) is the key.
 */
export type EventAttendee = {
  event_id: string       // FK → events.id
  user_id: string        // FK → profiles.id
  joined_at: string      // ISO 8601 — when the user joined
  team_number: number | null  // which team (1-based); null = unassigned
  team_pinned: boolean        // true if manually assigned by host; skipped during randomize
  status: 'attending' | 'waitlisted'
}

/** `event_attendees` row with embedded `profiles` from the event detail query (`profiles!…user_id…`). */
export type EventAttendeeWithProfile = EventAttendee & {
  profiles: Profile | null
}

/** Row shape from PostgREST embed `event_attendees(count)` (list/card queries). */
export type EventAttendeeCountEmbed = { count: number }

/**
 * `event_comments` table
 * Discussion thread on an event; one row per message.
 */
export type EventComment = {
  id: string
  event_id: string
  user_id: string
  body: string
  /** True when the event host posted this as an announcement (highlighted in UI). */
  is_announcement: boolean
  created_at: string
}

/** Comment row from Supabase with joined author profile (`profiles` null if author row missing). */
export type EventCommentWithAuthor = EventComment & {
  profiles: Pick<Profile, 'id' | 'username' | 'first_name' | 'last_name' | 'avatar_url' | 'selected_border'> | null
}

/**
 * `event_guests` table
 * A guest added as a +1 by an attending user. Has no profile/account.
 */
export type EventGuest = {
  id: string
  event_id: string
  added_by: string        // FK → profiles.id — the user who added them
  first_name: string
  last_name: string
  status: 'attending' | 'waitlisted'
  joined_at: string
  team_number: number | null
  team_pinned: boolean
}

/**
 * `event_cohosts` table
 * Up to 3 cohosts per event. Cohosts have the same permissions as the host.
 */
export type EventCohost = {
  event_id: string
  user_id: string
  added_by: string
  added_at: string
}

/** EventCohost with the cohost's profile embedded. */
export type EventCohostWithProfile = EventCohost & {
  profiles: Pick<Profile, 'id' | 'username' | 'first_name' | 'last_name' | 'avatar_url' | 'selected_border'>
}

/**
 * `feedback_submissions` table
 * Stores feature requests and bug reports submitted by users.
 */
export type FeedbackSubmission = {
  id: string
  user_id: string
  kind: FeedbackKind
  priority: FeedbackPriority
  title: string
  description: string
  created_at: string
}

export type FeedbackKind = 'feature' | 'bug'
export type FeedbackPriority = 'low' | 'medium' | 'high'

// ─── Query Response Types ─────────────────────────────────────────────────────
// These represent data returned by Supabase queries that JOIN related tables.
// The field names are determined by the Supabase query syntax, not renamed here.

/**
 * An event with its creator profile and attendee data pre-fetched.
 *
 * List/feed queries use `event_attendees_attending(count)` and `event_guests_attending(count)`
 * (one-element aggregates each) so “going” and spots match event detail.
 *
 * Event detail uses full rows: `event_attendees (event_id, user_id, …)` optionally with embedded `profiles`.
 */
export type EventWithDetails = Event & {
  profiles: Profile
  event_attendees?: EventAttendee[] | EventAttendeeCountEmbed[] | EventAttendeeWithProfile[]
  /** List/card queries only: attending RSVPs excluding waitlist. */
  event_attendees_attending?: EventAttendeeCountEmbed[]
  /** List/card queries only: attending +1 guests (excludes waitlisted guests). */
  event_guests_attending?: EventAttendeeCountEmbed[]
  /** List/card queries only: waitlisted RSVPs count. */
  event_attendees_waitlisted?: EventAttendeeCountEmbed[]
  event_tags?: { tag_id: string; tags: Tag }[]
  clubs?: { id: string; name: string; avatar_url: string | null } | null
}

// ─── Form Types ───────────────────────────────────────────────────────────────
// Represent the local state of input forms before data is sent to the database.

/** State used by the Create Event screen */
export type CreateEventForm = {
  title: string
  description: string
  location: string
  date: Date             // Stored as JS Date locally; converted to ISO string on submit
  durationMinutes: number      // Event duration; default 120
  maxAttendees: number | null  // null = unlimited
}

/**
 * `tags` table
 * Defines all available tags (e.g. skill levels, event types).
 * Grouped by `category` so new tag categories can be added without schema changes.
 */
export type Tag = {
  id: string
  name: string
  category: string      // e.g. 'skill_level', 'event_type'
  display_order: number
  created_at: string
}

/**
 * `user_event_templates` table
 * User-saved event templates for quickly re-hosting recurring events.
 */
export type UserEventTemplate = {
  id: string
  user_id: string
  name: string
  title: string
  description: string | null
  location: string | null
  max_attendees: number | null
  created_at: string
}

// ─── Club Types ───────────────────────────────────────────────────────────────

export type MembershipType = 'open' | 'invite'

/**
 * `clubs` table
 * A volleyball club with members and associated events.
 */
export type Club = {
  id: string
  name: string
  description: string | null
  membership_type: MembershipType
  created_by: string
  avatar_url: string | null
  cover_url: string | null
  created_at: string
}

/**
 * `club_members` join table
 * One row per (club, user) pair. Role is 'owner' for the creator and 'member' for others.
 */
export type ClubMember = {
  club_id: string
  user_id: string
  role: 'owner' | 'member'
  joined_at: string
}

/**
 * Club with its full member list (each member includes a partial profile embed).
 * Returned by queries that join club_members → profiles.
 */
export type ClubWithDetails = Club & {
  club_members: (ClubMember & {
    profiles: Pick<Profile, 'id' | 'username' | 'first_name' | 'last_name' | 'avatar_url'>
  })[]
}

// ─── Derived / Computed Types ─────────────────────────────────────────────────
// These are not stored in the database — they are calculated from the raw data
// for display purposes.

/**
 * Attendance summary for a single event, computed from EventWithDetails.
 * Used to drive the join/leave button states and spot count badges.
 */
export type AttendanceStatus = {
  count: number           // Total number of attendees currently signed up
  spotsLeft: number | null  // Remaining spots; null if the event has no cap
  isFull: boolean         // true when count >= max_attendees (and max_attendees is set)
  isAttending: boolean    // true if the current logged-in user is in event_attendees with status='attending'
  isOwner: boolean        // true if the current logged-in user created the event
  isWaitlisted: boolean       // true if the current user is on the waitlist
  waitlistPosition: number | null  // 1-based position on waitlist; null if not waitlisted
  waitlistCount: number       // total number of people on the waitlist
}

// ─── Badge Types ──────────────────────────────────────────────────────────────

export type CardBgType = 'ember' | 'frost' | 'aurora'

export type BadgeType =
  | 'event_attendee'
  | 'event_host'
  | 'cheers_received'
  | 'cheers_given'
  | 'spike_cheer'
  | 'serve_cheer'
  | 'block_cheer'
  | 'set_cheer'
  | 'dig_pass_cheer'
  | 'communication_cheer'
  | 'beta_tester'
  | 'tournament_director'
  | 'profile_complete'
  | 'vex_spirit'

/**
 * `user_badges` table
 * One row per (user, badge_type). Tier is upgraded in-place as the user levels up.
 */
export type UserBadge = {
  id: string
  user_id: string
  badge_type: BadgeType
  tier: number               // 1–5; most single-level badges are always 1
  awarded_at: string         // ISO 8601 — when this tier was reached
  display_order: number | null // 1, 2, or 3 if chosen for profile display; null otherwise
}
