// ─── Database Row Types ───────────────────────────────────────────────────────
// These mirror the Supabase (PostgreSQL) table schemas exactly.
// Each field name matches the database column name.

/**
 * `profiles` table
 * Created automatically by a database trigger when a user signs up via Supabase Auth.
 * The `id` matches `auth.users.id` (UUID).
 */
export type Profile = {
  id: string            // Primary key — same UUID as the auth user
  username: string      // Unique, lowercase display name chosen at registration
  avatar_url: string | null  // Optional profile picture (not yet used in UI)
  created_at: string    // ISO 8601 — when the account was created
}

/**
 * `events` table
 * Stores all events created by users.
 */
export type Event = {
  id: string                   // Primary key — UUID auto-generated by the DB
  created_by: string           // FK → profiles.id — the user who created this event
  title: string                // Required — shown everywhere an event is listed
  description: string | null   // Optional — longer details about the event
  location: string | null      // Optional — venue name or address
  event_date: string           // ISO 8601 — when the event takes place
  max_attendees: number | null // Optional capacity cap; null means unlimited
  created_at: string           // ISO 8601 — when this row was inserted
}

/**
 * `event_attendees` join table
 * One row per (event, user) pair. Inserting a row = joining an event.
 * Deleting a row = leaving an event.
 * There is no separate "attendee ID" — the composite (event_id, user_id) is the key.
 */
export type EventAttendee = {
  event_id: string  // FK → events.id
  user_id: string   // FK → profiles.id
  joined_at: string // ISO 8601 — when the user joined
}

// ─── Query Response Types ─────────────────────────────────────────────────────
// These represent data returned by Supabase queries that JOIN related tables.
// The field names are determined by the Supabase query syntax, not renamed here.

/**
 * An event with its creator profile and full attendee list pre-fetched.
 *
 * Returned by:
 *   supabase.from('events').select(`
 *     *,
 *     profiles!events_created_by_fkey (id, username, avatar_url),
 *     event_attendees (event_id, user_id, joined_at)
 *   `)
 *
 * - `profiles` is singular because every event has exactly one creator
 * - `event_attendees` is an array because an event can have many attendees
 */
export type EventWithDetails = Event & {
  profiles: Profile
  event_attendees: EventAttendee[]
}

// ─── Form Types ───────────────────────────────────────────────────────────────
// Represent the local state of input forms before data is sent to the database.

/** State used by the Create Event screen */
export type CreateEventForm = {
  title: string
  description: string
  location: string
  date: Date             // Stored as JS Date locally; converted to ISO string on submit
  maxAttendees: number | null  // null = unlimited
}

// ─── Derived / Computed Types ─────────────────────────────────────────────────
// These are not stored in the database — they are calculated from the raw data
// for display purposes.

/**
 * Attendance summary for a single event, computed from EventWithDetails.
 * Used to drive the join/leave button states and spot count badges.
 */
export type AttendanceStatus = {
  count: number           // Total number of attendees currently signed up
  spotsLeft: number | null  // Remaining spots; null if the event has no cap
  isFull: boolean         // true when count >= max_attendees (and max_attendees is set)
  isAttending: boolean    // true if the current logged-in user is in event_attendees
  isOwner: boolean        // true if the current logged-in user created the event
}
